---
recipe: default.v1
language: en
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "SpacyEntityExtractor"
    dimensions: ["PERSON", "LOC", "ORG"]
  - name: DIETClassifier
    epochs: 1
    ranking_length: 5
    batch_strategy: sequence
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
      - time
      - number
      - duration
      - amount-of-money
    locale: de_DE
    timezone: Europe/Berlin
    timeout: 3
  - name: DIETClassifier
    epochs: 1
    constrain_similarities: true
    batch_strategy: sequence
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies:
  - name: UnexpecTEDIntentPolicy
    epochs: 100
    max_history: 5
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    constrain_similarities: true
    epochs: 4
    batch_size: 50
    max_training_samples: 300
  - name: RulePolicy
    core_fallback_threshold: 0.3
    enable_fallback_prediction: True
    core_fallback_action_name: action_default_fallback
assistant_id: 20230723-171301-honest-limo
