---
recipe: default.v1
language: en
pipeline:
  - name: SpacyNLP
    model: en_core_web_md
    case_sensitive: false
  - name: SpacyTokenizer
    intent_tokenization_flag: false
    intent_split_symbol: _
    token_pattern: None
  - name: SpacyFeaturizer
    pooling: mean
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
    ranking_length: 5
    batch_strategy: sequence
  - name: SpacyEntityExtractor
    dimensions:
      - PERSON
      - FAC
      - GPE
      - LOC
      - DATE
      - ORG
      - MONEY
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
      - phone-number
      - number
      - amount-of-money
    locale: de_DE
    timezone: Europe/Berlin
    timeout: 3
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
    batch_strategy: sequence
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
    retrieval_intent: chitchat
  - name: ResponseSelector
    epochs: 300
    retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    constrain_similarities: true
    epochs: 400
    max_history: 6
    batch_size: 5
    max_training_samples: 30
  - name: RulePolicy
    core_fallback_threshold: 0.4
    enable_fallback_prediction: true
    core_fallback_action_name: action_default_fallback
assistant_id: 20240419-great-andes
