recipe: 'default.v1'
language: en
pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: "SpacyTokenizer"
  "intent_tokenization_flag": False
  "intent_split_symbol": "_"
  "token_pattern": None
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
  "BILOU_flag": true
- name: "SpacyEntityExtractor"
  dimensions: ["LOC"]
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - time
  - number
  - duration
  - amount-of-money
  locale: de_DE
  timezone: Europe/Berlin
  timeout: 3
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: chitchat
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
- name: AugmentedMemoizationPolicy
  max_history: 6
- name: TEDPolicy
  max_history: 5
  constrain_similarities: True
  epochs: 200
  batch_size: 50
  max_training_samples: 300
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
assistant_id: 20230723-171301-honest-limo