---
recipe: default.v1
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: null
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
    ranking_length: 5
    batch_strategy: sequence
  - name: DucklingEntityExtractor
    url: http://localhost:8000
    dimensions:
      - time
      - number
      - date
      - duration
      - amount-of-money
    locale: de_DE
    timezone: Europe/Berlin
    timeout: 3
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
    batch_strategy: sequence
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
    retrieval_intent: chitchat
  - name: ResponseSelector
    epochs: 200
    retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
policies:
  - name: UnexpecTEDIntentPolicy
    epochs: 200
    max_history: 8
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: TEDPolicy
    max_history: 5
    constrain_similarities: true
    epochs: 300
    batch_size: 50
    max_training_samples: 300
  - name: RulePolicy
    core_fallback_threshold: 0.3
    enable_fallback_prediction: True
    core_fallback_action_name: action_default_fallback
assistant_id: 20230723-171301-honest-limo
